#!/usr/bin/env python3
"""
jobStocksSignals.py
===================
Standalone cron job (no Streamlit) that:
  1. Loads STOCK_TICKERS from app.py, params from core.config (single source of truth)
  2. Builds stock signals table
  3. Computes macro regime (VIX + SPY vs 200MA + breadth) and adds Macro_Regime / Regime_Action columns
  4. Fetches Schwab holdings (QTY / VALUE) via saved tokens.json
  5. Merges them → outputs/merged_holdings_signals.csv + HTML + README
  6. Git commits & pushes to jobMyTrading repo

Cron on Pi (weekdays 6 AM PST = 14:00 UTC):
    0 14 * * 1-5 cd /home/rchak007/github/myTrading && .venv/bin/python jobStocksSignals.py >> /home/rchak007/github/jobMyTrading/job_stocks.log 2>&1
"""
from __future__ import annotations

import os
import sys
import json
import subprocess
import importlib.util
from pathlib import Path
from datetime import datetime, timezone

import pandas as pd
import numpy as np
import pytz

# -----------------------------
# Paths
# -----------------------------
MYTRADING_DIR = Path.home() / "github" / "myTrading"
JOB_DIR       = Path.home() / "github" / "jobMyTrading"

OUT_CSV     = JOB_DIR / "stocks_signals.csv"
OUT_HTML    = JOB_DIR / "stocks_signals.html"
OUT_README  = JOB_DIR / "README_stocks.md"
OUT_META    = JOB_DIR / "meta_stocks.json"
LOG_FILE    = JOB_DIR / "job_stocks.log"


# -----------------------------
# Logging
# -----------------------------
def log(msg: str):
    ts   = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    line = f"[{ts}] {msg}\n"
    print(line, end="")
    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        with LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(line)
    except Exception:
        pass


# -----------------------------
# Git helpers  (same as jobCryptoSignals.py)
# -----------------------------
def run_cmd(cmd: list[str], cwd: Path | None = None) -> tuple[int, str]:
    p = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return p.returncode, p.stdout


def git_has_changes(repo_dir: Path) -> bool:
    code, out = run_cmd(["git", "status", "--porcelain"], cwd=repo_dir)
    if code != 0:
        raise RuntimeError(f"git status failed:\n{out}")
    return out.strip() != ""


# -----------------------------
# HTML builder  (mirrors jobCryptoSignals.py style)
# -----------------------------
def build_html_table(df: pd.DataFrame, title: str, updated_pst: str) -> str:
    df2 = df.copy()

    # Format numeric columns
    for c in df2.columns:
        if c == "VALUE":
            df2[c] = pd.to_numeric(df2[c], errors="coerce").fillna(0.0).map(lambda v: f"${v:,.2f}")
        elif c == "QTY":
            df2[c] = pd.to_numeric(df2[c], errors="coerce").fillna(0.0).map(lambda v: f"{v:,.2f}")
        elif c in ("%RET30", "%RET60", "%RET90", "%RET120"):
            df2[c] = pd.to_numeric(df2[c], errors="coerce").map(
                lambda v: f"{v:+.2f}%" if pd.notna(v) else ""
            )

    cols = list(df2.columns)

    html = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>{title}</title>",
        "<style>",
        "body { font-family: Arial, sans-serif; margin: 16px; }",
        "h2 { margin-bottom: 6px; }",
        ".meta { color: #666; margin-bottom: 12px; }",
        "table { border-collapse: collapse; width: 100%; font-size: 13px; }",
        "th, td { border: 1px solid #ddd; padding: 5px 7px; }",
        "th { background: #f5f5f5; text-align: left; position: sticky; top: 0; }",
        "tr:nth-child(even) { background: #fafafa; }",
        ".num { text-align: right; font-variant-numeric: tabular-nums; }",
        ".exit { color: #c00; font-weight: 700; }",
        ".buy  { color: #080; font-weight: 700; }",
        ".small { font-size: 12px; color: #666; margin-top: 10px; }",
        "</style></head><body>",
        f"<h2>{title}</h2>",
        f"<div class='meta'>Last updated: <b>{updated_pst}</b></div>",
        "<table><thead><tr>",
    ]
    for c in cols:
        html.append(f"<th>{c}</th>")
    html.append("</tr></thead><tbody>")

    num_cols = {"VALUE", "QTY", "%RET30", "%RET60", "%RET90", "%RET120",
                "Score_30", "Score_60", "Score_90", "Score_120", "Score_Weighted",
                "Supertrend", "Last Close", "Current Price"}

    for _, row in df2.iterrows():
        sig = str(row.get("SIGNAL-Super-MOST-ADXR", ""))
        row_cls = " class='exit'" if "EXIT" in sig else (" class='buy'" if "BUY" in sig else "")
        html.append(f"<tr{row_cls}>")
        for c in cols:
            v = row.get(c, "")
            td_cls = " class='num'" if c in num_cols else ""
            html.append(f"<td{td_cls}>{v}</td>")
        html.append("</tr>")

    html.append("</tbody></table>")
    html.append("<div class='small'>Generated by Raspberry Pi daily job.</div>")
    html.append("</body></html>")
    return "\n".join(html)


# -----------------------------
# Schwab holdings  (clean, no st.* calls)
# -----------------------------
def fetch_schwab_holdings(app_mod) -> pd.DataFrame:
    """
    Pure-Python equivalent of app.py's fetch_schwab_stock_holdings().
    Reuses create_schwab_client / SchwabAuthError from app_mod's already-resolved imports.
    """
    from data.schwab.schwab_helper import create_schwab_client, SchwabAuthError

    TOKEN_PATHS = [
        MYTRADING_DIR / "tokens.json",
        MYTRADING_DIR / "data" / "schwab" / "tokens.json",
    ]
    USER_ID = "main"

    try:
        client_wrapper = create_schwab_client(USER_ID, TOKEN_PATHS, local_only=True)
        data = client_wrapper.fetch_positions()

        rows = []
        for acct in data:
            sa = acct.get("securitiesAccount", {})
            for pos in sa.get("positions", []) or []:
                inst       = pos.get("instrument", {}) or {}
                symbol     = inst.get("symbol")
                asset_type = inst.get("assetType")
                if asset_type not in ("EQUITY", "COLLECTIVE_INVESTMENT", "ETF"):
                    continue
                long_qty  = float(pos.get("longQuantity")  or 0.0)
                short_qty = float(pos.get("shortQuantity") or 0.0)
                mkt_value = float(pos.get("marketValue")   or 0.0)
                if symbol:
                    rows.append({"Ticker": symbol, "QTY": long_qty - short_qty, "VALUE": mkt_value})

        if not rows:
            log("⚠️  No equity positions found — holdings will be 0")
            return pd.DataFrame(columns=["Ticker", "QTY", "VALUE"])

        df = (
            pd.DataFrame(rows)
            .groupby("Ticker", as_index=False)
            .agg({"QTY": "sum", "VALUE": "sum"})
        )
        log(f"Schwab holdings: {len(df)} unique tickers")
        return df

    except SchwabAuthError as e:
        log(f"⚠️  Schwab auth error (token expired?): {e}")
        log("    Holdings will be empty. Copy fresh tokens.json from WSL after re-auth.")
        return pd.DataFrame(columns=["Ticker", "QTY", "VALUE"])

    except Exception as e:
        log(f"⚠️  Unexpected error fetching Schwab holdings: {e}")
        return pd.DataFrame(columns=["Ticker", "QTY", "VALUE"])


# -----------------------------
# Column reorder  (mirrors app.py logic exactly)
# -----------------------------
def reorder_columns(df: pd.DataFrame) -> pd.DataFrame:
    cols = list(df.columns)

    # ── Synced with app.py priority_cols (line ~669) ──
    priority_cols = [
        "QTY", "VALUE",
        "Score_30", "Score_60", "Score_90", "Score_120", "Score_Weighted",
        "%RET30", "%RET60", "%RET90", "%RET120",
        "Earnings_Alert", "Market_Cap_M",
    ]

    for c in priority_cols:
        if c in cols:
            cols.remove(c)

    insert_after = "SIGNAL-Super-MOST-ADXR"
    if insert_after in cols:
        idx = cols.index(insert_after) + 1
        for extra_col in reversed(priority_cols):
            if extra_col in df.columns:
                cols.insert(idx, extra_col)
    else:
        cols = ["Ticker", "QTY", "VALUE"] + priority_cols + [
            c for c in cols if c not in ("Ticker", "QTY", "VALUE") + tuple(priority_cols)
        ]

    for move_col in ["Timeframe", "Bar Time"]:
        if move_col in cols:
            cols.remove(move_col)
            cols.append(move_col)

    return df[[c for c in cols if c in df.columns]]


# -----------------------------
# Main
# -----------------------------
def main(no_push: bool = False):
    # Make sure myTrading modules are importable
    if str(MYTRADING_DIR) not in sys.path:
        sys.path.insert(0, str(MYTRADING_DIR))

    # ── Load config: params from core.config, tickers from app.py ──────────────
    from core.config import INDICATOR_PARAMS, MACRO_REGIME_OVERRIDE
    from core.macro import compute_macro_regime
    from data.stocks import build_stocks_signals_table, add_macro_regime_columns
    from data.breadth import fetch_vix_value, fetch_spy_vs_200ma, breadth_proxy_from_spy

    # Still need app.py for STOCK_TICKERS list and Schwab module ref
    try:
        spec = importlib.util.spec_from_file_location("myTrading_app", str(MYTRADING_DIR / "app.py"))
        mod  = importlib.util.module_from_spec(spec)
        assert spec and spec.loader
        spec.loader.exec_module(mod)
        STOCK_TICKERS = getattr(mod, "STOCK_TICKERS")
    except Exception as e:
        raise RuntimeError(f"Could not load STOCK_TICKERS from myTrading/app.py: {e}")

    pacific     = pytz.timezone("America/Los_Angeles")
    updated_pst = datetime.now(pacific).strftime("%Y-%m-%d %H:%M:%S %Z")

    log("=== jobStocksSignals.py start ===")
    log(f"Loaded {len(STOCK_TICKERS)} tickers from app.py")
    log(f"Params from core.config: ATR={INDICATOR_PARAMS['atr_period']}/{INDICATOR_PARAMS['atr_multiplier']}, "
        f"ADXR_LOW={INDICATOR_PARAMS['adxr_low_threshold']}")

    # ── 1. Build signals (using centralized params) ─────────────────────────────
    log("Computing stock signals...")
    df_signals = build_stocks_signals_table(
        STOCK_TICKERS,
        **INDICATOR_PARAMS,
    )
    log(f"Signals built: {len(df_signals)} rows")

    # ── 1b. Compute macro regime & add columns ─────────────────────────────────
    log("Computing macro regime...")
    try:
        vix = fetch_vix_value()
        spy_close, spy_ma200, spy_status = fetch_spy_vs_200ma()
        breadth = breadth_proxy_from_spy(spy_close, spy_ma200)

        macro_info = compute_macro_regime(
            vix=vix,
            spy_above_200ma=(spy_status == "ABOVE"),
            breadth_pct=breadth["pct"],
            override=MACRO_REGIME_OVERRIDE,
        )
        macro_regime = macro_info["regime"]
        log(f"Macro regime: {macro_regime} — {macro_info['reason']}")
    except Exception as e:
        log(f"⚠️  Macro regime computation failed: {e} — defaulting to NEUTRAL")
        macro_regime = "NEUTRAL"
        macro_info = {"regime": "NEUTRAL", "reason": f"Fallback (error: {e})", "risk_pct": 1.0}

    df_signals = add_macro_regime_columns(df_signals, macro_regime)
    log(f"Macro columns added: Macro_Regime={macro_regime}")

    # ── 2. Fetch Schwab holdings ────────────────────────────────────────────────
    df_holdings = fetch_schwab_holdings(mod)

    # ── 3. Merge ────────────────────────────────────────────────────────────────
    df = df_signals.merge(df_holdings, on="Ticker", how="left")
    df["QTY"]   = df["QTY"].fillna(0)
    df["VALUE"] = df["VALUE"].fillna(0.0)
    df = reorder_columns(df)
    log(f"Merged: {len(df)} rows, {len(df.columns)} columns")

    # ── 4. Write outputs ────────────────────────────────────────────────────────
    JOB_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)

    html = build_html_table(df, title="Stock Signals + Schwab Holdings", updated_pst=updated_pst)
    OUT_HTML.write_text(html, encoding="utf-8")

    # Summary stats
    held      = df[df["VALUE"] > 0]
    exits     = df[df.get("SIGNAL-Super-MOST-ADXR", pd.Series(dtype=str)).str.contains("EXIT", na=False)]
    total_val = float(df["VALUE"].fillna(0).sum())

    meta = {
        "updated_at_pst": updated_pst,
        "macro_regime": macro_regime,
        "macro_reason": macro_info["reason"],
        "macro_risk_pct": macro_info.get("risk_pct", 0),
        "tickers_scanned": len(df_signals),
        "tickers_held": len(held),
        "total_portfolio_value": total_val,
        "exit_signals": list(exits["Ticker"]) if not exits.empty else [],
    }
    OUT_META.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    readme = f"""# Stock Signals Snapshot

Last updated: **{updated_pst}**

## Market Regime
- **Macro Regime:** {macro_regime}
- **Risk per trade:** {macro_info.get('risk_pct', 0)}%
- **Reason:** {macro_info['reason']}

## Portfolio Summary
- **Tickers scanned:** {len(df_signals)}
- **Tickers held:** {len(held)}
- **Total portfolio value:** ${total_val:,.2f}
- **EXIT signals:** {", ".join(meta["exit_signals"]) or "none"}

## Table
Open **stocks_signals.html** in the repo for the formatted table.

(Generated daily from Raspberry Pi — weekdays ~6 AM PST.)
"""
    OUT_README.write_text(readme, encoding="utf-8")
    log("Outputs written: csv / html / readme / meta")

    # ── 5. Git commit & push ────────────────────────────────────────────────────
    if no_push:
        log("--no-push flag set — skipping git commit/push.")
        log("=== jobStocksSignals.py done ===")
        return

    code, _ = run_cmd(["git", "rev-parse", "--is-inside-work-tree"], cwd=JOB_DIR)
    if code != 0:
        log("jobMyTrading is not a git repo — skipping push.")
        return

    if not git_has_changes(JOB_DIR):
        log("No changes detected — skipping commit/push.")
        return

    run_cmd(["git", "add", "-A"], cwd=JOB_DIR)
    msg = f"Daily stocks snapshot: {updated_pst}"
    code, out = run_cmd(["git", "commit", "-m", msg], cwd=JOB_DIR)
    if code != 0:
        log(f"git commit failed:\n{out}")
        return

    code, out = run_cmd(["git", "push", "origin", "main"], cwd=JOB_DIR)
    if code != 0:
        log(f"git push failed:\n{out}")
        return

    log("Pushed to GitHub ✅")
    log("=== jobStocksSignals.py done ===")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-push", action="store_true",
                        help="Skip git commit/push (useful for local testing)")
    args = parser.parse_args()

    try:
        main(no_push=args.no_push)
    except Exception as e:
        log(f"FATAL: {repr(e)}")
        raise